export const mockUsers = [
  {
    id: "U0001458",
    name: "Mark Smith",
    email: "marksmith@gmail.com",
    phone: "856 856 8569",
    policy: "Student Policy",
  },
  {
    id: "U0002459",
    name: "John Mathew",
    email: "john@gmail.com",
    phone: "9876543210",
    policy: "Faculty Policy",
  },
];

export const mockBooks = [
  {
    title: "The Time Traveler",
    author: "Mark Smith",
    year: "2021",
    rfid: "A1B2C3D4E5",
    totalCopies: 100,
    availableCopies: 75,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    copies: [
      {
        rfid: "A1B2C3D4E5",
        status: "Available",
        dueDate: null,
        fine: 0,
      },
      {
        rfid: "A1B2C3D4E6",
        status: "Issued",
        dueDate: "23-11-2025",
        fine: 0,
        userId: "U00014855",
        userName: "John Smith",
        renewalCount: 1,
        maxRenewals: 3,
        overdueDays: 0,
        statusBadge: "On-Time",
      },
      {
        rfid: "A1B2C3D4E7",
        status: "Issued",
        dueDate: "23-11-2025",
        fine: 30,
        userId: "U00014856",
        userName: "William",
        renewalCount: 3,
        maxRenewals: 3,
        overdueDays: 5,
        statusBadge: "Overdue",
      },
      {
        rfid: "A1B2C3D4E8",
        status: "Issued",
        dueDate: "25-11-2025",
        fine: 0,
        userId: "U00014857",
        userName: "Sarah Johnson",
        renewalCount: 0,
        maxRenewals: 3,
        overdueDays: 0,
        statusBadge: "On-Time",
      },
    ],
  },
  {
    title: "The Two Towers",
    author: "J.R.R. Tolkien",
    year: "1954",
    rfid: "RFID00124",
    totalCopies: 50,
    availableCopies: 30,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    copies: [
      {
        rfid: "RFID00124",
        status: "Available",
        dueDate: null,
        fine: 0,
      },
      {
        rfid: "RFID00125",
        status: "Issued",
        dueDate: "20-03-2026",
        fine: 50,
        userId: "U0001458",
        userName: "Mark Smith",
        renewalCount: 2,
        maxRenewals: 3,
        overdueDays: 0,
        statusBadge: "On-Time",
      },
    ],
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: "1937",
    rfid: "RFID00126",
    totalCopies: 75,
    availableCopies: 50,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    copies: [
      {
        rfid: "RFID00126",
        status: "Available",
        dueDate: null,
        fine: 0,
      },
      {
        rfid: "RFID00127",
        status: "Issued",
        dueDate: "15-03-2026",
        fine: 30,
        userId: "U0002459",
        userName: "John Mathew",
        renewalCount: 1,
        maxRenewals: 3,
        overdueDays: 0,
        statusBadge: "On-Time",
      },
    ],
  },
];