import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { NextAuthProvider } from "@/providers/SessionProvider";
import { PermissionProvider } from "@/providers/PermissionProvider";
import { Poppins } from "next/font/google";
import "./globals.css";
export const dynamic = "force-dynamic";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Library Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <PermissionProvider>{children}</PermissionProvider>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
